server:
  port: 8080
  url:

local:
  port: 8080
  url: http://localhost:8080


spring:
  jackson:
    time-zone: Asia/Seoul
  application:
    name:ds-helper
  datasource:
    url: jdbc:mysql://localhost:3306/ds-helper
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

jakarta:
  persistence:
    jdbc:
      url: jdbc:mysql://localhost:3306/ds_helper

# swagger
springdoc:
  api-docs:
    #    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger # 루트 경로로 접근 시 swagger 경로 자동 라우팅
    #    config-url: /v3/api-docs/swagger-config
    #    url: /v3/api-docs
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
#    disable-swagger-default-url: true

#mail url
mail:
  redirect:
    url: http://localhost:8080

kakao:
  client:
    id: edda215e7bcfbe5fe5d504c7039fe035
    secret: 7myEWId37nBy6AvZmqTlmP5s1YTCZFRT
  redirect:
    uri: http://localhost:8080/oauth/kakao/login

cloud:
  aws:
    credentials:
      access-key: YOUR_AWS_ACCESS_KEY
      secret-key: YOUR_AWS_SECRET_KEY
    region:
      static: ap-northeast-2 # 서울
    stack:
      auto: false

s3:
  bucket: your-bucket-name

file:
  upload:
    max-size: 3MB
    max-request-size: 30MB
    allowed-file-extensions: jpg,jpeg,png


